In [1]:
import pandas as pd

In [5]:
col1 = [1,2,3,4,5]
col2 = [45,56,67,34,34]
col3 = ["sudhansu", "kumar", "krish", "inueron", "one"]


df = pd.DataFrame({"col1": col1,
              "col2":col2,
              "col3":col3})

In [6]:
def test(a):
  return a**2

In [8]:
df['col4_4'] = df['col1'].apply(test)

In [9]:
df

   col1  col2      col3  col4_4
0     1    45  sudhansu       1
1     2    56     kumar       4
2     3    67     krish       9
3     4    34   inueron      16
4     5    34       one      25

In [11]:

def test1(a):
  if a=='s':
    return 's'
  else:
    return 'z'



df['col6'] = df['col3'].str[0].apply(test1)
df

   col1  col2      col3  col4_4 col6
0     1    45  sudhansu       1    s
1     2    56     kumar       4    z
2     3    67     krish       9    z
3     4    34   inueron      16    z
4     5    34       one      25    z

In [13]:
df['col6_6'] = df['col3'].str[0].apply(lambda a:'s' if a=='s' else 'z')
df

   col1  col2      col3  col4_4 col6 col6_6
0     1    45  sudhansu       1    s      s
1     2    56     kumar       4    z      z
2     3    67     krish       9    z      z
3     4    34   inueron      16    z      z
4     5    34       one      25    z      z

In [18]:
df['col5'] = df['col3'].str[0]

df

   col1  col2      col3  col4_4 col6 col6_6 col5
0     1    45  sudhansu       1    s      s    s
1     2    56     kumar       4    z      z    k
2     3    67     krish       9    z      z    k
3     4    34   inueron      16    z      z    i
4     5    34       one      25    z      z    o

In [19]:
df['col7'] = df['col3'].apply(len)

In [20]:
df

   col1  col2      col3  col4_4 col6 col6_6 col5  col7
0     1    45  sudhansu       1    s      s    s     8
1     2    56     kumar       4    z      z    k     5
2     3    67     krish       9    z      z    k     5
3     4    34   inueron      16    z      z    i     7
4     5    34       one      25    z      z    o     3

In [23]:
import math

df['col8'] = df['col2'].apply(math.log)

In [24]:
df

   col1  col2      col3  col4_4 col6 col6_6 col5  col7      col8
0     1    45  sudhansu       1    s      s    s     8  3.806662
1     2    56     kumar       4    z      z    k     5  4.025352
2     3    67     krish       9    z      z    k     5  4.204693
3     4    34   inueron      16    z      z    i     7  3.526361
4     5    34       one      25    z      z    o     3  3.526361

In [25]:
import numpy as np

In [33]:
dict = {"age":35, "ram":"name"}

In [30]:
print(dict.items())
print(dict.values())

dict_items([('age', 35), ('ram', 'name')])
dict_values([35, 'name'])

In [32]:
dict.pop("age")
dict

{'ram': 'name'}

In [34]:
lis = ["age",35, "ram","name"]

In [37]:
lis.count(35)

1

In [57]:
def addNumbers(**kwarg):
  r = 0
  print("Inside")
  for i in kwarg:
    print( i, kwarg[i])

dic = {"Name":"Derek", "Age":35, "YearBorn":1974}
print(addNumbers(dic)) 
  
  
#   return num1+num2

# def main():
#   print(addNumbers)

# if __name__=='__main__':
#   print(main())

# print(addNumbers())

Inside
Name Derek
Age 35
YearBorn 1974
None